font_size 18.0

# font_family      SpaceMono Nerd Font Book
# bold_font        SpaceMono Nerd Font Medium
# italic_font      SpaceMono Nerd Font Book Italic
# bold_italic_font SpaceMono Nerd Font Medium Italic
font_family      Caskadia Mono Nerd Font Regular
bold_font        Caskadia Mono Nerd Font Bold
italic_font      Caskadia Mono Nerd Font Italic
bold_italic_font Caskadia Mono Nerd Font Bold Italic

disable_ligatures never

scrollback_lines 2000

url_color #0087bd
url_style curly

open_url_modifiers kitty_mod
open_url_with default

detect_urls yes

copy_on_select no

#: How much to dim text that has the DIM/FAINT attribute set. One
#: means no dimming and zero means fully dimmed (i.e. invisible).

selection_foreground #000000

#: The foreground for text selected with the mouse. A value of none
#: means to leave the color unchanged.

selection_background #fffacd

#: The background for text selected with the mouse.

mark1_foreground black

#: Color for marks of type 1

mark1_background #98d3cb

#: Color for marks of type 1 (light steel blue)

mark2_foreground black

#: Color for marks of type 2

mark2_background #f2dcd3

#: Color for marks of type 1 (beige)

mark3_foreground black

#: Color for marks of type 3

mark3_background #f274bc

#: Color for marks of type 1 (violet)
