font_size 18.0

font_family      Operator Mono Book
bold_font        Operator Mono Medium
italic_font      Operator Mono Book Italic
bold_italic_font Operator Mono Medium Italic

disable_ligatures never

scrollback_lines 2000

url_color #0087bd
url_style curly

open_url_modifiers kitty_mod
open_url_with default

detect_urls yes

copy_on_select no

#: How much to dim text that has the DIM/FAINT attribute set. One
#: means no dimming and zero means fully dimmed (i.e. invisible).

selection_foreground #000000

#: The foreground for text selected with the mouse. A value of none
#: means to leave the color unchanged.

selection_background #fffacd

#: The background for text selected with the mouse.


#: The 16 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version. You can also set the remaining colors from
#: the 256 color table as color16 to color255.

color0       #00384d
color8       #517f8d

#: black

color1       #c43061
color9       #ff5a67

#: red

color2       #7fc06e
color10      #9cf087

#: green

color3       #f08e48
color11      #ffcc1b

#: yellow

color4       #1c8db2
color12      #7eb2dd

#: blue

color5       #c694ff
color13      #fb94ff

#: magenta

color6       #00cccc
color14      #00ffff

#: cyan

color7       #77929e
color15      #b7cff9

#: white

mark1_foreground black

#: Color for marks of type 1

mark1_background #98d3cb

#: Color for marks of type 1 (light steel blue)

mark2_foreground black

#: Color for marks of type 2

mark2_background #f2dcd3

#: Color for marks of type 1 (beige)

mark3_foreground black

#: Color for marks of type 3

mark3_background #f274bc

#: Color for marks of type 1 (violet)
